### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by f4n0** [JalmarazMartn/customDiagnostics#1]
Hi, 
I would like to create some errors for wrong app.json properties, is it possible? 

Could you please share to me an example of the file? is this extension always enabled or I need to do something? 

Thanks

**Comment by JalmarazMartn** [comment]
I am very interested too in json files diagnostics. From monday i will check it and will tell you something about that.

Thank you for the feed-back!!

PD: Could help if you send an example with the diagnostic you want to set.

**Comment by f4n0** [comment]
Thanks a lot! 
My colleagues started talking about being sure that every app must have the same URLs and to be sure of the right ContextSensitiveHelpUrl, and then I remembered your app and I think that could solve loads of problems!

**Comment by JalmarazMartn** [comment]
I activated events for the language json to solve this, and uploading the version 13 with the change. Anyway, not sure if this can solve the issue completly. So the issue will stay open until next week when I test your use case.

**Comment by f4n0** [comment]
Well, thanks a lot! 
are you coming to BC Tech Days?

**Comment by JalmarazMartn** [comment]
I don't, but looks great. Enjoy if you go.

**Comment by JalmarazMartn** [comment]
With the release I published last day we can check json files and raise error for diagnostic rules in these files.

The bad news are that the regular expression that matches with "ContextSensitiveHelpUrl" without having "YourRightUrl.com" doesn´t work.

if I have this setting:

            {
                "code": "F4N0-01",
                "message": "Control json Context URL",                
                "searchExpresion": "^(?!.*YourUrl.*).*contextSensitiveHelpUrl.*$",
                "severity": "error",
                "language": "json"
            }            
The search expression must match when doesn´t exists "YourUrl" and exists "contextSensitiveHelpUrl" in the string. If I set one of them ^(?!.*YourUrl.*) or .*contextSensitiveHelpUrl.* it works, but not the two conditions together.

I keep working on this but if you have any idea of set this regexp in other way tell me.

Best regards and thank you. The issue wil be still open.

**Comment by JalmarazMartn** [comment]
Forget previous request. I saw one thing to fix this.

**Comment by JalmarazMartn** [comment]
And done. The extension is fixed to search these negative clause diagnostics. I will keep the issue open a couple of days to be sure and then I will close it.

Thank you for your contribution, makes the extension better.

**Comment by JalmarazMartn** [comment]
And done. The extension is fixed to search this negative clause diagnostics. I will keep the issue open a couple of days to be sure and then I will close it.

Thank you for your contribution, makes the extension better.

**Comment by JalmarazMartn** [comment]
And done. The extension is fixed to search this negative clause diagnostics. I will keep the issue open a couple of days to be sure and then I will close it.

Thank you for your contribution, makes the extension better.

**Comment by f4n0** [comment]
thanks to you and for the fast support!
Have a nice day!!

**Comment by JalmarazMartn** [comment]
I did a change in this feature that could be good for you:

Instead of setting exclusion in the regular expression you have the option to simplify this kind of expression with a new property of diagnostics: "skipFromSearchIfMatch".

So you can set the previous diagnostic this way:

{
            "code": "F4N0-01",
            "message": "Control json Context URL",                
            "searchExpresion": "contextSensitiveHelpUrl",
            "skipFromSearchIfMatch": "YourUrl",
            "severity": "error",
            "language": "json"
}

This can help you to set diagnostics, easier and cleaner. Thank you again for your feedback.
