### ISSUE TITLE
Cannot find module 'typescript' error when trying to apply fixes

### ISSUE THREAD

**Issue by gengyj16** [JalmarazMartn/customDiagnostics#2]
applyFixes.js line 1: `const { escapeLeadingUnderscores } = require('typescript');` invokes `Cannot find module 'typescript' Require stack: ......` error when trying to apply fixes.
After deleting this line, the problem disappeared. I'm not familiar with JavaScript, is it ok to do this?

**Comment by gengyj16** [comment]
![image](https://github.com/user-attachments/assets/d400f7ae-1c1d-4b18-a383-9c8c7778c65c)

**Comment by JalmarazMartn** [comment]
Fixed. 

You were right: this line was the kind-of-shit-that-js-writes-by-its-own. 

Thank you very much.
